-- MySQL Script generated by MySQL Workbench
-- Sun Jan  5 20:55:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema csdl_dangnhap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csdl_dangnhap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csdl_dangnhap` DEFAULT CHARACTER SET latin1 ;
USE `csdl_dangnhap` ;

-- -----------------------------------------------------
-- Table `csdl_dangnhap`.`taikhoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdl_dangnhap`.`taikhoan` (
  `idDangNhap` INT(11) NOT NULL,
  `userName` VARCHAR(20) NULL DEFAULT NULL,
  `password` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idDangNhap`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
